version: "3"
name: "owl"
services:
  app:
    container_name: owl-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5173:5173
      - 9323:9323
    volumes:
      - ../:/home/owl/dev
      - ./bin/root:/sbin/root
      - ./bin/owl:/usr/local/bin/owl
    tty: true
    deploy:
      resources:
        limits:
          cpus: "4.0"
          memory: 8G
        reservations:
          cpus: "2.0"
          memory: 4G
